module.exports = [
  {
    title: 'Do Push Ups, Sit Ups, and Pull Ups',
    points: 3,
    proofRequired: false,
    pool: 'Health',
  },
  {
    title: 'Reach out to a Friend',
    points: 5,
    proofRequired: false,
    pool: 'Social',
  },
  {
    title: 'Go out to lunch with a biz Contact',
    points: 3,
    proofRequired: false,
    pool: 'Social',
  },
  {
    title: 'Play Fetch with hatch',
    points: 1,
    proofRequired: false,
    pool: 'Happy',
  },
  {
    title: 'Eat a Vegetable',
    points: 1,
    proofRequired: false,
    pool: 'Health',
  },
  {
    title: 'Cook Dinner',
    points: 5,
    proofRequired: false,
    pool: 'Health',
  },
  {
    title: 'Go see a Movie',
    points: 1,
    proofRequired: false,
    pool: 'Social',
  },
  {
    title: 'Say How Im Feeling',
    points: 1,
    proofRequired: false,
    pool: 'Emotion',
  },
  {
    title: 'Give a Compliment',
    points: 1,
    proofRequired: false,
    pool: 'Emotion',
  },
  {
    title: 'Give a Hug',
    points: 1,
    proofRequired: false,
    pool: 'Emotion',
  },
  {
    title: 'Do Homework',
    points: 1,
    proofRequired: false,
    pool: 'Social',
  },
  {
    title: 'Clean Room',
    points: 1,
    proofRequired: false,
    pool: 'Social',
  },
  {
    title: 'Play a Fun Game',
    points: 1,
    proofRequired: false,
    pool: 'Happy',
  },
  {
    title: 'Eat Fruit',
    points: 1,
    proofRequired: false,
    pool: 'Health',
  },
  {
    title: 'Jumping Jacks',
    points: 1,
    proofRequired: false,
    pool: 'Health',
  },
];
